assetic:
  java: /usr/bin/java
  filters:
    cssembed:
      jar: %kernel.root_dir%/Resources/java/cssembed-0.4.5.jar
    yui_js:
      jar: %kernel.root_dir%/Resources/java/yuicompressor.jar
    lessphp:
      file: %kernel.root_dir%/../vendor/oyejorge/less.php/lessc.inc.php
      apply_to: "\.less$"
  assets:
    bootstrap_js:
        inputs:
            - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/transition.js'
            - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/alert.js'
            - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/modal.js'
            - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/dropdown.js'
            - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/scrollspy.js'
            - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/tab.js'
            - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/tooltip.js'
            - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/popover.js'
            - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/button.js'
            - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/collapse.js'
            - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/carousel.js'
            - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/affix.js'
        filters: [?yui_js]
    bootstrap_less:
        inputs:
            - '%kernel.root_dir%/../vendor/twitter/bootstrap/less/bootstrap.less'
        filters: [lessphp, cssrewrite]
    glyphicons_svg:
        inputs:
            - '%kernel.root_dir%/../vendor/twitter/bootstrap/fonts/glyphicons-halflings-regular.svg'
        output: "fonts/glyphicons-halflings-regular.svg"
    glyphicons_ttf:
        inputs:
            - '%kernel.root_dir%/../vendor/twitter/bootstrap/fonts/glyphicons-halflings-regular.ttf'
        output: "fonts/glyphicons-halflings-regular.ttf"
    glyphicons_woff:
        inputs:
            - '%kernel.root_dir%/../vendor/twitter/bootstrap/fonts/glyphicons-halflings-regular.woff'
        output: "fonts/glyphicons-halflings-regular.woff"
    glyphicons_eot:
        inputs:
            - '%kernel.root_dir%/../vendor/twitter/bootstrap/fonts/glyphicons-halflings-regular.eot'
        output: "fonts/glyphicons-halflings-regular.eot"
