parameters:
    manager.user.class: Realtor\DictionaryBundle\Model\UserManager
    app.password.encoder.class: Application\Sonata\UserBundle\Service\MessageDigestPasswordEncoder
    manager.dictionary.branch.class: Realtor\DictionaryBundle\Model\BranchManager
    manager.call.action.class: Realtor\CallBundle\Model\CallManager
    call.listener.class: Realtor\CallBundle\Listeners\CallListener
    manager.dictionary.advertising_source.class: Realtor\DictionaryBundle\Model\AdvertisingSourceManager
    authentication_handler.class: Application\Sonata\UserBundle\Handlers\AuthenticationHandler

services:
    manager.user:
        class: %manager.user.class%
        arguments:
            - http://disp.emls.ru/api/employee
            - @doctrine.orm.entity_manager
            - @validator
            - @fos_user.user_manager
    manager.dictionary.branch:
        class: %manager.dictionary.branch.class%
        arguments:
            - http://disp.emls.ru/api/branches
            - @doctrine.orm.entity_manager

    manager.dictionary.advertising_source:
        class: %manager.dictionary.advertising_source.class%
        arguments:
            - http://disp.emls.ru/api/advertising_source
            - "@doctrine.orm.entity_manager"

    manager.call.action:
        class: %manager.call.action.class%
        arguments:
            - http://188.227.101.17:8080 #http://192.168.251.16:8080
            - @logger
        tags:
            - { name: monolog.logger, channel: call_ats_action }

    app.password.encoder:
        class: %app.password.encoder.class%

    monolog.handler.elastic_persistent:
        class: System\Log\ElasticHandler
        calls:
            - [setLogDir, [%kernel.logs_dir%]]

    call.listener:
        class: %call.listener.class%
        arguments:
            - "@service_container"
        tags:
            - { name: doctrine.event_listener, event: preRemove }

    authentication_handler:
        class: %authentication_handler.class%
        arguments:  [@router]
        calls:
            - [setHttpUtils, [@security.http_utils]]
            - [setHttpKernel, [@http_kernel]]
            - [setLogger, [@logger]]
            - [setOptions, [{}]]
            - [setValidator, [@validator]]
            - [setEntityManager, [@doctrine.orm.entity_manager]]
        tags:
            - { name: "monolog.logger", channel: "security" }