parameters:
    manager.user.class: Realtor\DictionaryBundle\Model\UserManager

services:
    manager.user:
        class: %manager.user.class%
        arguments:
            - http://disp.emls.ru/api/employee
            - @doctrine.orm.entity_manager
            - @validator