parameters:
    manager.user.class: Realtor\DictionaryBundle\Model\UserManager
    app.password.encoder.class: Application\Sonata\UserBundle\Service\MessageDigestPasswordEncoder
    manager.dictionary.branch.class: Realtor\DictionaryBundle\Model\BranchManager
    manager.call.action.class: Realtor\CallBundle\Model\CallManager

services:
    manager.user:
        class: %manager.user.class%
        arguments:
            - http://disp.emls.ru/api/employee
            - @doctrine.orm.entity_manager
            - @validator
    manager.dictionary.branch:
        class: %manager.dictionary.branch.class%
        arguments:
            - http://disp.emls.ru/api/branches
            - @doctrine.orm.entity_manager

    manager.call.action:
        class: %manager.call.action.class%
        arguments:
            - http://188.227.101.17:8080
            - @logger
        tags:
            - { name: monolog.logger, channel: call_ats_action }

    app.password.encoder:
        class: %app.password.encoder.class%

    monolog.handler.elastic_persistent:
        class: System\Log\ElasticHandler
        calls:
            - [setLogDir, [%kernel.logs_dir%]]