parameters:
    manager.user.class: Realtor\DictionaryBundle\Model\UserManager
    app.password.encoder.class: Application\Sonata\UserBundle\Service\MessageDigestPasswordEncoder

services:
    manager.user:
        class: %manager.user.class%
        arguments:
            - http://disp.emls.ru/api/employee
            - @doctrine.orm.entity_manager
            - @validator

    app.password.encoder:
        class: %app.password.encoder.class%