parameters:
#    admin.example.class: Realtor\AdminBundle\Example

services:
#    admin.example:
#        class: %admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    admin.admin.advertising_source:
        class: Realtor\AdminBundle\Admin\AdvertisingSourceAdmin
        arguments:
            - ~
            - Realtor\DictionaryBundle\Entity\AdvertisingSource
            - SonataAdminBundle:CRUD
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Справочники", label: "Источники рекламы"}

    admin.admin.branches:
        class: Realtor\AdminBundle\Admin\BranchesAdmin
        arguments:
            - ~
            - Realtor\DictionaryBundle\Entity\Branches
            - SonataAdminBundle:CRUD
        calls:
            - [ setSecurityContext, [@security.context]]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Справочники", label: "Филиалы"}

    admin.admin.reason:
        class: Realtor\AdminBundle\Admin\ReasonAdmin
        arguments:
            - ~
            - Realtor\DictionaryBundle\Entity\Reason
            - SonataAdminBundle:CRUD
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Справочники", label: "Причина обращения"}

    admin.admin.call_result:
        class: Realtor\AdminBundle\Admin\CallResultAdmin
        arguments:
            - ~
            - Realtor\DictionaryBundle\Entity\CallResult
            - SonataAdminBundle:CRUD
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Справочники", label: "Результат разговора"}

    admin.sonata.block.numberpad:
        class: Realtor\AdminBundle\Block\NumberPad
        arguments:
            - @sonata.block.service.rss
            - @templating
        tags:
            - {name: sonata.block}

    admin.sonata.block.call_card:
        class: Realtor\AdminBundle\Block\CallCard
        arguments:
            - admin.sonata.block.call_card
            - @templating
            - @doctrine.orm.entity_manager
        calls:
            - ["setCallDialUpEvent", [%call.dial_up.event%]]
            - ["setCallDialDownEvent", [%call.dial_down.event%]]
        tags:
            - {name: sonata.block}

    admin.admin.black_list:
        class: Realtor\AdminBundle\Admin\BlackListAdmin
        arguments:
            - ~
            - Realtor\CallBundle\Entity\BlackList
            - SonataAdminBundle:CRUD
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Черный список", label: "Черный список"}

    admin.admin.duty:
        class: Realtor\AdminBundle\Admin\DutyAdmin
        arguments:
            - ~
            - Application\Sonata\UserBundle\Entity\Duty
            - SonataAdminBundle:CRUD
        calls:
            - [ setSecurityContext, [@security.context]]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "График дежурств", label: "График дежурств" }
