<?php

namespace Realtor\DictionaryBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BranchesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BranchesRepository extends EntityRepository
{
    public function getBranchByPhone($phone)
    {
        $builder = $this->getEntityManager()->createQueryBuilder()
            ->select('branches')
            ->from('DictionaryBundle:Branches', 'branches')
            ->where('branches.branchNumber = :phone')
            ->setParameter('phone', $phone);

        try{
            $result = $builder->getQuery()->getResult();
        }
        catch(NoResultException $e){
            $result = null;
        }

        return $result;
    }
}
