<?php

namespace Realtor\CallBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * AtsCallsDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AtsCallsDataRepository extends EntityRepository
{
    public function getAtsCallsData($limit, $offset)
    {
        $builder = $this->getEntityManager()->createQueryBuilder()
            ->select(
                [
                    'ats_calls_data.nrec',
                    'ats_calls_data.callDate',
                    'ats_calls_data.callTime',
                    'ats_calls_data.clid',
                    'ats_calls_data.src',
                    'ats_calls_data.dst',
                    'ats_calls_data.dcontext',
                    'ats_calls_data.channel',
                    'ats_calls_data.dstchannel',
                    'ats_calls_data.lastapp',
                    'ats_calls_data.lastdata',
                    'ats_calls_data.duration',
                    'ats_calls_data.billsec',
                    'ats_calls_data.disposition',
                    'ats_calls_data.amaflags',
                    'ats_calls_data.accountcode',
                    'ats_calls_data.uniqueid',
                    'ats_calls_data.userfield',
                    'ats_calls_data.xTag',
                    'ats_calls_data.xCid',
                    'ats_calls_data.xDid',
                    'ats_calls_data.xDialed',
                    'ats_calls_data.xSpec',
                    'ats_calls_data.xInsecure',
                    'ats_calls_data.xResult',
                    'ats_calls_data.xRecord',
                    'ats_calls_data.xDomain',
                    'ats_calls_data.linkedid',
                ]
            )
            ->from('CallBundle:AtsCallData', 'ats_calls_data')
            ->setMaxResults($limit)->setFirstResult($offset)
            ->orderBy('ats_calls_data.nrec')
        ;

        try{
            $result = $builder->getQuery()->getArrayResult();
        }
        catch(NoResultException $e){
            $result = null;
        }

        return $result;
    }

    public function getCountAtsCallsData()
    {
        $builder = $this->getEntityManager()->createQueryBuilder()
            ->from('CallBundle:AtsCallData', 'ats_calls_data')
        ;

        $builder->select($builder->expr()->count('ats_calls_data.id'));

        try{
            $result = $builder->getQuery()->getSingleScalarResult();
        }
        catch(NoResultException $e){
            $result = null;
        }

        return $result;
    }
}
