<?php

namespace Realtor\CallBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserPhonesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserPhonesRepository extends EntityRepository
{
    public function removePhonesByUser($userId)
    {
        $this->getEntityManager()->createQuery("DELETE CallBundle:UserPhones u WHERE u.userId = :userId")
            ->setParameter('userId', $userId)->execute();
        return;
    }
}
